# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    place_service:
        class: AppBundle\Service\PlaceService
        arguments: ["@doctrine.orm.entity_manager"]
