version: '2'

services:

### Workspace Utilities Container ###########################


### MariaDB Container #######################################

    mariadb:
        build: ./mariadb
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root


### phpMyAdmin Container ##################################

    phpmyadmin:
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        volumes_from:
            - volumes_data
        ports:
            - "8080:80"
        links:
            # for mysql container
            # - "mysql:db"
            # for mariadb container
            - "mariadb:db"
    volumes_source:
            image: tianon/true
            volumes:
                - ../:/var/www/symfony3-rest


    volumes_data:
            image: tianon/true
            volumes:
                - ./data/mysql:/var/lib/mysql
                - ./data/postgres:/var/lib/postgresql/data
                - ./data/memcached:/var/lib/memcached
                - ./data/redis:/data
                - ./data/neo4j:/var/lib/neo4j/data
                - ./data/mongo:/data/db
                - ./data/aerospike:/opt/aerospike/data
                - ./data/sessions:/sessions
                - ./data/caddy:/root/.caddy
                - ./data/elasticsearch/data:/usr/share/elasticsearch/data
                - ./data/mailcatcher/data:/usr/share/mailcatcher/data